### ISSUE TITLE
试用了一下，报错了？

### ISSUE THREAD

**Issue by elover** [totorojs/totoro-server#61]
mactekiMacBook-Pro-3:~ mac$ totoro-server --verbose
debug index.js:40 | Fail to read config file <totoro-server-config.json>
debug index.js:40 | Fail to read config file <totoro-server-config.json>
info index.js:69 | Start server 172.16.130.5:9999
info labor.js:40 | New labor {"laborId":"P5kMaOp5ruMCjvDRV6gv","ua":"firefox 22.0 / macosx 10.8"}
connect mongo server error!
info labor.js:40 | New labor {"laborId":"bSXu1KqV74uyv_DcV6gw","ua":"chrome 34.0.1766.0 / macosx 10.8.3"}

浏览器能显示对

但是运行demo的时候报错

mactekiMacBook-Pro-3:mocha mac$ totoro
info handle-cfg.js:151 | Found runner </Users/mac/Documents/totoro/examples/mocha/tests/runner.html>
error index.js:165 | Server is not available, please check your config or try again later.
Call Stack:
    at SocketNamespace.<anonymous> (/usr/local/lib/node_modules/totoro/lib/index.js:165:16)
    at SocketNamespace.EventEmitter.emit [as $emit](/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/lib/events.js:165:15)
    at Socket.publish (/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/lib/socket.js:103:19)
    at Socket.onError (/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/lib/socket.js:462:10)
    at xhr.onreadystatechange (/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/lib/socket.js:165:40)
    at dispatchEvent (/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:519:25)
    at setState (/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:538:14)
    at handleError (/usr/local/lib/node_modules/totoro/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:463:5)

**Comment by elover** [comment]
补充一点 totoro config详情
mactekiMacBook-Pro-3:mocha mac$ totoro config

  server-host={{http://172.16.130.5:9999}}

**Comment by fool2fish** [comment]
`{{your-server-host}}` 整个是一个变量啦

```
$ totoro config --server-host=172.16.130.5
```

这里的 host 就是严格意义的host，如果port也不是默认值的话，需要这么设置：

```
$ totoro config --server-port={{your-server-port}}
```

**Comment by elover** [comment]
哦哦，谢谢沉鱼mm
